### ISSUE TITLE
feature: Use WebCatalog prefix to store multisite workspace in %appdata%

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1033]
# Feature Request
**Specifications:**
- App Version: 24.7.0
- OS (macOS, Windows, Linux): Windows

**Description:**
When creating a multisite workspace, it gets installed in %appdata% (<user>/AppData/Roaming). The name of the folder that is used, is the name of the multisite app. To avoid (unlikely) name clashes, but also to better distinct those folders, I would prefer if these created folders were prefixed (with for instance WebCatalog-).

**Comment by quanglam2807** [comment]
This is definitely necessary to improve the app's integrity. Still, how should we deal with backward compatibility? 

Ref: https://www.electronjs.org/docs/api/app#appsetpathname-path

**Comment by Woafmann** [comment]
Yes, I noticed the same thing in MacOS: Multi-site app folders are created with the multi-site app name and strewn about in "~/Library/Application Support". It does seem somewhat messy this way and could cause naming conflicts.

An elegant solution IMO would be to keep the same app names for the folders as they are currently, but place all those app folders under a master "WebCatalog Apps" folder instead of being in the root "Application Support" or "AppData/Roaming" directories. It will be less cluttered than adding prefixes and I imagine will take less work to implement since with prefixes, the app folders would then be different names than the actual apps themselves. 

If this is not possible, then prefixes will be a workable alternative solution, albeit not as organized IMO.

**Comment by ghost** [comment]
I agree with @Woafmann on using a sub-folder strategy making more sense than the prefix.
