### ISSUE TITLE
feature: Ability to add WordPress based blog site

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#1034]
# Feature Request
**Specifications:**
- App Version: 24.7.0
- OS (macOS, Windows, Linux): Windows

**Description:**
I would like to have the ability to add my personal WordPress blog as app. Of course this could be done using a custom app, but I can imagine this could be offered as a standard app for people to add their own blogs in WebCatalog. Not sure if this should be submitted as a standard Catalog App request though (the URL would be just for my blog in this case).

The pattern could be extended to other similar 'personal' web application installations like forums, blogs etc.

**Comment by quanglam2807** [comment]
Thank you for bringing this up.

This has been in my mind for some time. And probably, @marcusquinn is interested in this as well. One way of adding support for WordPress blogs and other self-hosted apps to the catalog would be something like this:

In the database, each self-hosted app would have a wildcard URL, something like **\*.wordpress.org** or **\*.nextcloud.org**.
In the app, for these apps, instead of having "Install" buttons, we would show "Customize". Clicking on it would prompt the user to modify the URL before proceeding to install.

**Comment by quanglam2807** [comment]
Also, since WebCatalog is becoming like an app store, so I think allowing blog sites to be added is actually a good idea.

**Comment by ekamran** [comment]
As a full time WordPress Enthusiast, I'm in for this feature. I can certainly create a completely custom multisite app managing all my personal & client websites.

This made me think, if it's possible that ONE SPECIFIC Custom Workspace can have a completely different USER-AGENT?

User-Agent is based on the entire Multisite App but not for a specific Workspace.

**Comment by quanglam2807** [comment]
@ekamran Yes, it’s possible. Per-workspace user agent feature is in the prerelease channel. Just switch it on in WebCatalog’s preferences page

**Comment by quanglam2807** [comment]
https://webcatalog.io/webcatalog/apps/wordpress-admin/
