### ISSUE TITLE
feature: add NixOS support

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#1104]
# Bug Report
**Specifications:**
- App Version:
- OS (macOS, Windows, Linux): Linux

**Description:**

> Only place i'm running into issues is on nixOS, which is because of AppImage compat issues, broadly. I'd love it if there was a way to run this on NixOS in a sane way; i've looked into appimage-run as a work around, which unfortunately doesn't appear to work. Josiah

**Steps to Reproduce:**

**Additional Context**

**Comment by jowj** [comment]
Been playing with this some. No progress to report, really, but here's some additional context:

I originally thought that `appimage-run` was breaking because its just a very simple work around, but I replicate the same behavior when I (naively) try and emulate other appimage builds from  nixpkgs in a Webcatalog derivation. I will use `appimage-run` examples in this comment since I'm getting the same behavior in my attempted pkg. Its easier to replicate with `appimage-run`. The only difference is that my custom pkg has the errors coming from a different location in my local nixstore.

`appimage-run` is a tool for one off running of appimages on NixOS. Using this, we can open web catalog, like this:
![2020-12-05-130954_1276x1417_scrot](https://user-images.githubusercontent.com/14844361/101261224-3c392000-36fb-11eb-8b82-0f56b8d9f656.png)

Two things stand out to me:
1. `APPIMAGE env is not defined, current application is not an AppImage` - dunno if this is indicative of a problem at all.

2. `/home/josiah/.cache/appimage-run/0b38985cea7ced97a4bc2b611a0b52c4b019b687fc0be76b6466d622a7c73c58/webcatalog: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory`

This is the blocking error as far as I can tell; this triggers whenever I install an app or click update. Upon "install" nothing seems to happen, I can't open the newly installed WebCatalog Sub App at all; clicking "open" does nothing. Clicking "update" also does nothing, but triggers this same missing library warning.

I tried fucking with LD_LIBRARY_PATH and providing a folder that houses the proper libgojbect file, but I still get an error loading libraries. I'm out of my element here, but hopefully this is enough info that someone can point me in the right direction.

**Comment by quanglam2807** [comment]
Thank you for the efforts, @jowj! 

Based on this thread: https://github.com/AppImage/AppImageKit/issues/472, it seems like AppImage won't be a good choice to run WebCatalog on NixOS.

I just have a look at VSCode nixpkg: https://github.com/NixOS/nixpkgs/tree/master/pkgs/applications/editors/vscode. It seems like the script simply downloads the tarball (tar.gz) of VSCode, moves the files to the right place, create desktop file and that's it. So I'll try to release WebCatalog as tarball in next major update. Then we can create WebCatalog nixpkg based on VSCode's.

**Comment by quanglam2807** [comment]
I've pushed initial code for webcatalog nixpkg: https://github.com/NixOS/nixpkgs/pull/106458

I'm currently not using NixOS so I haven't tested it out yet (in fact, I've never used NixOS). If somebody is nice enough to finish the work, that'd be great.

Feel free to email at quang.lam@webcatalog.app and I'll give you write access to the PR.
