### ISSUE TITLE
Google will discontinue support for sign-ins to Google accounts from embedded browser frameworks, starting January 4, 2021.

### ISSUE THREAD

**Issue by marcusquinn** [webcatalog/webcatalog-legacy#1182]
Just received this email from our Google Dev account, thought it might be relevant:

![image](https://user-images.githubusercontent.com/6428977/99422794-d0cc1180-28f7-11eb-8a81-b28ae74c4be3.png)
![image](https://user-images.githubusercontent.com/6428977/99422938-f0fbd080-28f7-11eb-99db-838786659fef.png)

**Comment by quanglam2807** [comment]
Thank you, @marcusquinn!

Actually, they've started blocking people from signing in with Chromium/Electron-based browsers for some time. I'm not sure what would change exactly after 2021.  Currently, WebCatalog bypasses this by changing UA string to of legacy Microsoft Edge (non-Chromium) but I'm not sure how long the workaround would last.

I think Google has some kind of signature check on Chromium-based browser but has no way to do it with Firefox/legacy Edge. 

I'll close this thread for now as the fix is already in place (well, unless Google decides to wreck havoc again).
