### ISSUE TITLE
feature: Use system menu 

### ISSUE THREAD

**Issue by fakhamatia** [webcatalog/webcatalog-legacy#1311]
# Feature Request
**Specifications:**
- App Version: 28.0.1
- OS: Linux

**Description:**
Use system menu for apps, but not system theme like Telegram
I want system menu for always on top

**Additional Context**
![Screenshot from 2021-01-25 15-48-59](https://user-images.githubusercontent.com/20030910/105705357-59cd7d80-5f25-11eb-9318-6857fe06ad52.png)

**Comment by zocker-160** [comment]
There is a workaround for this: when you enable the system title bar and borders, then you will have the system menu like on any other application in your system.

You can find it under Preferences > Advanced > Use system title bar and borders -> Enable

**Comment by quanglam2807** [comment]
Thank you, @zocker-160. I'll close this issue.

**Comment by F50Ci37Y** [comment]
It's not the same thing.
If I enable `Use system title bar and borders` its changing decoration, it changes this:
![image](https://user-images.githubusercontent.com/20030910/121588863-a7b5ce80-ca4b-11eb-9be3-85b0d6a0dbfc.png)
To This:
![image](https://user-images.githubusercontent.com/20030910/121589639-8f927f00-ca4c-11eb-8ab6-72877c2f668f.png)
it's ugly! because showing menu bar and height 3 times before.
But Telegram has its own UI and OS menu.
Even not using OS theme, because my OS theme its this:
![image](https://user-images.githubusercontent.com/20030910/121589681-9c16d780-ca4c-11eb-8711-c5a8e3ff34b5.png)

**Comment by zocker-160** [comment]
@fakhamatia I you find your default window system title bar and borders ugly, then you should change them in the system to not be ugly, because the application itself has no influence on the look of it.

Furthermore I have provided a workaround for exactly your issue in order to get the system menus working, disliking that because of looks, which the application cannot influence, is disingenuous.

**Comment by F50Ci37Y** [comment]
@zocker-160 
It's not the same thing.
You do not answer. You covering the problem.
Sweeping under the carpet.

**Comment by zocker-160** [comment]
@fakhamatia but you have to accept the developer's choice that saw my workaround as good enough to close this feature request.
