### ISSUE TITLE
feature: proxy support

### ISSUE THREAD

**Issue by Beurling** [webcatalog/webcatalog-legacy#1391]
# Feature Request
**Specifications:**
- App Version:30.2.1
- OS (Windows,):

**Description:**
proxy is a vital function.why just remove it? many app is not working now.

**Comment by quanglam2807** [comment]
We decided to remove the feature because we couldn't ensure the proxy settings are applied everywhere in the app. This could confuse and give the wrong security expectations that all network requests in the app are made through the proxy. 

We'll try to bring it back in the near future when we figure out how to implement it more properly.

**Comment by Beurling** [comment]
> We decided to remove the feature because we couldn't ensure the proxy settings are applied everywhere in the app. This could confuse and give the wrong security expectations that all network requests in the app are made through the proxy.
> 
> We'll try to bring it back in the near future when we figure out how to implement it more properly.

Thank you.I really love this app!

**Comment by quanglam2807** [comment]
Thank you for your patience. Proxy support has been added back with https://github.com/webcatalog/neutron/pull/390
