### ISSUE TITLE
Swiping to navigate doesn't work when sidebar is hidden

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#211]
https://github.com/quanglam2807/webcatalog/issues/174#issuecomment-471525130

**Comment by quanglam2807** [comment]
@dave-redfern I just tested it on Macbook and it seemed to be fixed. Probably, it was a bug in the previous version of Electron.

**Comment by dave-redfern** [comment]
@quanglam2807 Hmm, I'm up-to-date with the current stable release, but the gestures still don't work for me. Opera actually exhibits the same problem. The keyboard shortcut Cmd+[ works, so I'm using that.

I wonder if deleting any app config data may help or did you use a recently compiled unreleased version?

**Comment by quanglam2807** [comment]
@dave-redfern Thanks a lot for the quick reply! I tested with the latest released version. Have you changed the macOS preferences as instructed? Electron doesn't support two-finger swiping so it's quite annoying that way.

Hopefully, this might be added soon: https://github.com/electron/electron/issues/2683

**Comment by dave-redfern** [comment]
I have "Swipe between pages" set to use 3-finger swipe. I find 2 fingers triggers too much since I tend to rest my hand on the trackpad. I then map "Swipe between full-screen apps" to 4 fingers since I hardly ever use multiple desktops or full screen apps.

**Comment by quanglam2807** [comment]
@dave-redfern Thank you for getting back!! It's the same pref I use.

I just tested more carefully. It seems like it only works when the sidebar is shown. Would you mind trying that on your Mac?

**Comment by dave-redfern** [comment]
@quanglam2807 LOL! It's working now with the sidebar enabled! hahahahaahaha, that is so totally random. Any idea why having the side bar enabled would suddenly make it work?

**Comment by quanglam2807** [comment]
@dave-redfern Haha. I got it. So basically, when the sidebar is shown, the title bar is hidden so the default behavior of Electron is to allow you to swipe anywhere in the window. But when the sidebar is shown, the title bar is shown, so you can only swipe when your mouse is on the title bar. Is this good enough for you? If not, I can write some code to replace the default title bar.

**Comment by dave-redfern** [comment]
Not sure I follow the latter point. If the sidebar is hidden and the titlebar is shown, swiping does not work, even if you place the cursor in the title bar. If both sidebar and titlebar are enabled, then swiping works and again if sidebar on it's own is enabled.

I can manage with the sidebar open; I had closed it to free up horizontal space since I don't have multiple Jira / GitHub accounts (I run 3 web apps side-by-side on a 3440x1440 desktop).

Re: fixes; requiring specific placement of the cursor would be a worse fix than leaving the sidebar open IMHO. Though I am in favour of whatever is the least hacky way of handling this, that causes the least amount of knock-on issues 😄

**Comment by quanglam2807** [comment]
@dave-redfern :) Hmm, as I tested, if you leave the cursor on the title bar, swiping should work. Anyway, I'm working on a fix. It'll be available soon.
