### ISSUE TITLE
Reduce individual app sizes

### ISSUE THREAD

**Issue by floriandierickx** [webcatalog/webcatalog-legacy#281]
Every installed app takes around 280 MB of space. When using proprietary alternatives or @jiahaog [nativefier](https://github.com/jiahaog/nativefier) versions of some apps, size is usually much less. Is there a way to share resources between apps / reduce the size? When installing lots of apps the total WebCatalog folder gets quite big.

For example:

- Facebook messenger -> Caprine = 147 MB
- Twitter -> Twitter (made with nativefier) = 125 MB
- Gmail -> Gmail (made with nativefier) = 125 MB
- Telegram -> Telegram (official) = 67 MB
- Google Calendar -> Google Calendar (nativefier) = 114 MB
- Todoist -> Todoits (official) = 26 MB
- Slack -> Slack (official) = 191 MB
- Skype -> Skype (official) = 230 MB

For Trello the official app is larger (332 MB)

**Comment by quanglam2807** [comment]
Back in v9 or v10, I don't remember exactly, I managed to bring the app sizes down to around 20-30 MB an app by sharing the Electron engine between the apps. I decided to remove the features because it was too cumbersome to maintain and ensure it works on all devices. As the app was recently ported to Linux and Windows, please give me some time to ensure everything is working correctly before working on this issue. :) TDLR: It's possible but it takes time.
