### ISSUE TITLE
Add autofill login in the App

### ISSUE THREAD

**Issue by Flewim** [webcatalog/webcatalog-legacy#294]
Hi, is there no way to save a log in an app? I have to log in multiple time in a day on my website. I just want the system to save the login information (like 1Password, iCloud Keychain..).
Thanks in advance.
Florian

**Comment by quanglam2807** [comment]
Thank you for asking! 
This is related to #161. While this feature sounds simple, implementing it might be challenging because WebCatalog would have to store the passwords somewhere and if it is not implemented correctly, it might lead to security issues. So I hope you would rather spend some more time to log in every day than to risk your security.

Still, if anything changes in the future, I'll definitely add the feature.

**Comment by Flewim** [comment]
> Thank you for asking!
> This is related to #161. While this feature sounds simple, implementing it might be challenging because WebCatalog would have to store the passwords somewhere and if it is not implemented correctly, it might lead to security issues. So I hope you would rather spend some more time to log in every day than to risk your security.
> 
> Still, if anything changes in the future, I'll definitely add the feature.

Hi Quang Lam,
Thank you for your reply.
