### ISSUE TITLE
Too much updating, and background updater is suspect

### ISSUE THREAD

**Issue by beorn** [webcatalog/webcatalog-legacy#361]
Almost every 2-3 days my webapps stop working because they need to be updated, and when I try to update them it says I need to update WebCatalog, and when I update WebCatalog (from within the WebCatalog app) the update never seems to finish.  I end up having to go to getwebcatalog.com and re-installing it from there every time.

1. Does the background updater even work?  Is it possible to add a progress bar or log something to the system log to troubleshoot?

2. It seems like most I end up updating both the apps and WebCatalog every time, which is a bit of a pain.  What's the point of having to update the apps separately from WebCatalog if you end up updating both at the same time anyways?

**Comment by bigbang11** [comment]
I agree, it is the first app I have seen which updating this way and you don't have any look how far the update is and so I feel like I have no control over it. suspect is a good description
<img width="912" alt="Bildschirmfoto 2019-11-06 um 19 44 11" src="https://user-images.githubusercontent.com/57227590/68327715-29a28080-00ce-11ea-9cf8-2f78a6f08523.png">

**Comment by quanglam2807** [comment]
Thank you for the feedback. You're the first people who're annoyed by this issue and personally, I'm annoyed too. It is my top priority at the moment so I'll try to address it ASAP.

**1. Does the background updater even work? Is it possible to add a progress bar or log something to the system log to troubleshoot?** Certainly, it does but the app size is too large to get it done in an acceptable. Also, I understand nobody leaves the main WebCatalog app open for long to wait for updates. I'll update the UI to show the download progress. 

**2. It seems like most I end up updating both the apps and WebCatalog every time, which is a bit of a pain. What's the point of having to update the apps separately from WebCatalog if you end up updating both at the same time anyways?** This is because of the way apps are created at the moment. When you create an Electron app with WebCatalog, the app would run completely independently from WebCatalog so it needs to be regenerated every time an update is available. This could be fixed by sharing app resources between apps and the main WebCatalog app, but I haven't figured out an optimal way to do this.

**3. Update notifying dialog on app startup**. At the moment, you can turn off automatic update checking on startup on the preferences page of each app.

**Comment by bigbang11** [comment]
hello Quanglam, thanks for your quick response. it's just an unusual approach for software updates. I for my part have never seen anything like this before and I like to control my computer and it seems strange to me when a program says it has downloaded an update and tells me at some point when it is ready to install it and nothing happens, or you can't see what's happening. You can imagine it like a visit announcing itself, but you don't know when it will be there. I can't say much more about this app because I only downloaded it a day ago, but at first glance I like the clean design and so far everything has worked according to my wishes.

**Comment by quanglam2807** [comment]
@bigbang11 Actually, many Mac apps are downloading updates in the background these days (Slack, GitHub Desktop, VS Code, etc). I think the problem is that WebCatalog doesn't provide a good way for user to check the updating progress and what the app is doing in the background. I would be honest that I did not do it properly in the name of saving time. I'll fix it soon :)

**Comment by beorn** [comment]
@quanglam2807 Thanks!  That'll help a lot!

I guess some ideas (not sure if they'll work technically or from a monetization point of view):

- Install webcatalog through Mac App Store or Homebrew, and rely on their update mechanisms
- Have a background service that updates the app - and also updates the webapps?
- Have a background webapp service inside of every webapp that updates that webapp

**Comment by quanglam2807** [comment]
@beorn Thanks for the suggestions. It's possible to add WebCatalog to Homebrew Cask. But this process is not fully automated I guess so I would be quite a burden for me. Mac App Store option is unlikely to happen as WebCatalog is not that well-sandboxed.

The web apps are mostly identical with the same Electron engine and the JS code inside. Each app is built on top of a template app with some additional files to customize it. So theoretically, the template app could be updated independently from WebCatalog but executing it would be challenging because of code signing and other stuff. For example, you can have a signed app, but when you customize it with certain files, the signing would then be broken. So I don't think it'd be better to keep the app the way it is for some time.

**Comment by ghost** [comment]
this is happening on my linux machine too.  Seems to indicate the update was downloaded and I restart, but nothing happens.  WebCatalog still has a bunch of processes running in the background. I've let it sit for awhile to see if it was just a slow update, but eventually killed it and restarted webcatalog and no update was applied.  I've updated manually the last two updates. I was trying to see where the updates are being downloaded but could not.

**Comment by quanglam2807** [comment]
I've released v17.4.0 with the mentioned updater's improvements. I'll leave this issue open for some time to see if everything works correctly and as expected.

**Comment by ghost** [comment]
on linux the update process seems to work except for the restarting.  After accepting close and restart, it does not restart automatically. It has the same behavior, where webcatalog process continues to hang.  After killing and restarting manually, the update was applied just fine.  I ran the 17.3 from the command line and this is the out put I got up to the hang: 

downloading byterange = ......

```
Error: Error: ENOENT: no such file or directory, chmod '/home/adev/.cache/webcatalog-updater/pending/temp-WebCatalog-17.4.0.AppImage'
(node:5564) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chmod '/home/adev/.cache/webcatalog-updater/pending/temp-WebCatalog-17.4.0.AppImage'
(node:5564) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, chmod '/home/adev/.cache/webcatalog-updater/pending/temp-WebCatalog-17.4.0.AppImage'
(node:5564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code


Install on explicit quitAndInstall
Error: Error: No valid update available, can't quit and install
    at AppImageUpdater.install (/tmp/.mount_webcatfOGzEU/resources/app/node_modules/electron-updater/out/BaseUpdater.js:61:26)
    at AppImageUpdater.quitAndInstall (/tmp/.mount_webcatfOGzEU/resources/app/node_modules/electron-updater/out/BaseUpdater.js:28:30)
    at Immediate._onImmediate (/tmp/.mount_webcatfOGzEU/resources/app/build/libs/updater.js:87:23)
    at processImmediate (internal/timers.js:439:21)

```

I don't know js at all to understand this.  But, like I said after manually killing the process and restarting, the update does apply just fine.  Also, for some reason the 'Update is available and is being downloaded' window hangs around after webcatalog closes after user accepts restart. Not sure if the two are related.

**Comment by quanglam2807** [comment]
@dankworks Thanks for reporting! This seems like a quite common bug with `electron-updater`. I'll look at the workarounds to see what would be the best solution.

https://github.com/electron-userland/electron-builder/issues/3402#
https://github.com/electron-userland/electron-builder/issues/3269

**Comment by quanglam2807** [comment]
Is this issue totally resolved for you, guys? I thought I had resolved this but a user just emailed to complain that they cannot use their apps without updating. I guess it's because he uses the main WebCatalog app as app launcher and the UI doesn't show the "Open" button when an update is available. I've fixed that. 

Still, if there's anything else, please let me know. I want to fix this once and for all. More people are using the app and there're feature requests coming so I'd love to release updates quickly without disrupting the experience.

**Comment by beorn** [comment]
It seems to be working fine for me!  I can use the apps, but I get a popup saying a new update is available in WebCatalog, and when I open WebCatalog it updates itself, and afterward a restart I’m able to “UPDATE ALL” the web apps.

Thanks for making it so much smoother. 🙂

(One somewhat unrelated question I always have is whether I need to quit the web apps when they are being updated.  I don’t always do that, and there are no warnings, but I’m used to the system Software Updater complaining about that so I have always suspected maybe I should.  Maybe possible to say something about this somewhere in the UI?)

**Comment by quanglam2807** [comment]
@beorn Thanks for the response! Honestly, I always keep the apps running when updating. I think you can do that on Mac. I guess when you open an app, macOS basically loads the app into memory first, so it doesn't matter if you modify the *.app file. I find it quite convenient so if it doesn't have any bad consequences, I'd leave it that way :)
