### ISSUE TITLE
Add ability to import and export apps

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#378]

**Comment by linonetwo** [comment]
1. What does export apps mean?
1. If I share a generated app to my friend, does this violate the License?

**Comment by marcusquinn** [comment]
Assuming you mean import and export app setup settings for name, category, URL & icon - and not the whole App itself?

**Comment by quanglam2807** [comment]
I'm so sorry for only replying to this after 5 months... For this feature, I'm thinking about exporting app info like name, URL, icon, etc & app preferences. You can use the backup files to restore all these apps later.

**Comment by scgilardi** [comment]
I'd very much like to have this feature or one like it. It can take a fair amount of time to configure an app with several workspaces. I'd like a way to share my suite of apps easily among all my Macs. Export/Import is one way. Being able to make a git repo of some directory that only contains config (and is therefore reasonably sized) would be another. Actual sharing of an iCloud Drive config directory would be the easiest I can think of, but seems the most challenging to implement due to concurrency concerns.

**Comment by quanglam2807** [comment]
Thank you so much for the feedback. We’ll take it into consideration and try to work on the feature/bug fix in the future. 

For now, we’ll close this issue as we’re replacing GitHub Issues with other tools to help our team to streamline, better coordinate, and scale our operations. If you have feedback or questions, feel free to contact us at https://webcatalog.io/contact/.
