### ISSUE TITLE
feature: brew cask

### ISSUE THREAD

**Issue by ghost** [webcatalog/webcatalog-legacy#540]
# Feature Request
Would it be possible to recreate the webcatalog brew cask that was removed at some point for easier installation? (https://github.com/Homebrew/homebrew-cask/pull/42135)

**Describe Preferred Solution**
Create a cask, so it can be installed with:
brew cask install webcatalog

**Describe Alternatives**

**Additional Context**

**Comment by quanglam2807** [comment]
Thank you for the suggestion! I'd love to add the app to brew cask. It's quite simple but it's quite time consuming to do it manually after every update so I'll see if I can automate the process.

**Comment by ghost** [comment]
Based on the other casks that are from GitHub, if you put in the feed URL, their bot auto updates the cask

**Comment by quanglam2807** [comment]
Thank you! I'm writing the formula! Should `brew cask` uninstall apps installed with WebCatalog as well? I'm thinking about not doing so as these apps can work independently from WebCatalog.

**Comment by dave-redfern** [comment]
@quanglam2807 I'd say leave the apps or if possible prompt if you want them removing; failing that a note that says the Apps need remove from %install_dir%.

**Comment by quanglam2807** [comment]
@dave-redfern Thank you for the suggestion! I'll leave the apps for now. It's probably too complicated to add prompts as I don't even know how to add it to the cask.

**Comment by vitorgalvao** [comment]
Homebrew Cask maintainer here.

> Based on the other casks that are from GitHub, if you put in the feed URL, their bot auto updates the cask

That’s incorrect. We don’t have a bot to auto-update casks. We have a bot that auto-*merges* when certain conditions are met.

> it's quite time consuming to do it manually after every update so I'll see if I can automate the process.

See [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask). After a short initial setup, and assuming your URL keeps the same structure, all you have to do to update the cask in the future is run `cask-repair --cask-version NEW_VERSION --blind-submit webcatalog`. That single command will do everything: create a new branch, update the cask, push it, send a PR. You can add it to your build script.

Note that at an unspecified time in the future the initial setup will need to run again, because currently I’m relying on `hub` to make the PR but I plan on changing that.

**Comment by quanglam2807** [comment]
@vitorgalvao Thanks a lot for the clarification! It really helps.

I'm trying to integrate Homebrew with the build script but I received this error: `No such cask was found in any official repo (webcatalog).`. What should I do? Here is the build script: https://github.com/quanglam2807/webcatalog/blob/cask/.github/workflows/macos.yml#L49

I run the same commands locally and they work perfectly.

**Comment by quanglam2807** [comment]
Ah, I found it. GitHub Actions sets `HOMEBREW_NO_AUTO_UPDATE=1` by default. So `brew update` needs to be run manually.
