### ISSUE TITLE
Add tab support

### ISSUE THREAD

**Issue by mr-mmmmore** [webcatalog/webcatalog-legacy#62]
Hi,

I love webcatalog and to be able to package any web app into a desktop app. After having using it for a while I have bought the full licence.

But there is a bug that defeats one of the purpose of the app: when trying to open a link in a tab by using either cmd+click or the contextual menu, the link opens in a new window. This defeats one of webcatalog benefits: to be able to access the whole context of a web app in a single window.

It would be great if link could simply open as tab.

I am using WebCatalog Lite 12.3.1 on Mac OS 10.13.4.

**Comment by quanglam2807** [comment]
Are you using Juli or Chrome as the engine? I'll try to add tab support for Juli or add Firefox support #7 to resolve this issue.

**Comment by mr-mmmmore** [comment]
I am using Chrome.

**Comment by quanglam2807** [comment]
@mr-mmmmore I'll look into this.

**Comment by Erudition** [comment]
What would be the point of this? If you need to open an external link, it should be in a separate window (or separate browser). If you need to open an internal link separately, you're probably dealing with a website and not a real web app.

If you add tabbed browsing, you have an ordinary browser all over again!

**Comment by mr-mmmmore** [comment]
The vast majority of desktop apps allow you to have several files open at the same time, often in the same window...

What is the point of this ? To be able to work on several contexts at the same time without having to leave a given one, to be able to switch from one to another easily.

A web app is an app after all, why shouldn't it benefit from what we have learn about efficiency when working with desktop apps?

Plus you don't have to decide for me if I **should** open a link in a tab or in a window, wether it is external or not, I use tabs, if I can (with Fluid for example), in many web apps I use. Even browsers, which are originally meant for "websites", don't try to force you in a way or another, you can decide, wether you're on a a website or a web app...

**Comment by Erudition** [comment]
@mr-mmmmore 
> Even browsers, which are originally meant for "websites", don't try to force you in a way or another, you can decide, wether [sic] you're on a a website or a web app...

Because browsers are meant for websites, and web apps came into existence despite that. Websites also revolve around _links_, web apps do not, so not having a feature that was designed for links (most web apps show no links at all, just buttons) is not "forcing you" to do anything. The whole point of webcatalog is to be built for web apps (only), not websites. Browsers evolved to have tabs so that you can have multiple documents open at a time, like other document-managing applications - and websites are normally not built for handling that natively. 

Single-page apps, however, are not. They should already have a tab-like functionality if that makes sense for the purpose. For example, [Messenger](messenger.com) shows your conversations in the responsive side panel, which you can easily switch between just like tabs. If you want two conversations on screen at the same time, you open a new window simply by launching another instance of the webapp, then you can choose a different conversation. But as soon as you want to merge those two windows into one with tabs to switch between them (which you can do in KDE Plasma, for instance) - you have defeated the point of separate windows, and you might as well switch conversations the normal way!

That said, feel free to provide your use case. Perhaps there is something that definitely fits the category of "web app" but is also definitely designed to be used multi-instance with browser tabs. I just haven't found any.

> The vast majority of desktop apps allow you to have several files open at the same time

Well, no, actually, most desktop apps don't even deal with "files" to be "open". Skype. Discord (which is just a web app). System Settings. There are no files to switch between. And when there are...

> often in the same window...

Then they already provide a mechanism to tab between interfaces! Terminal. Word Processor. File manager. Blender. Apps that need tabs, tend to provide them. Same goes for web apps. Messenger. Google Calendar. Slack. They may not look like or be called "tabs", however.

> To be able to work on several contexts at the same time without having to leave a given one, to be able to switch from one to another easily.

Again, If you really want to arbitrarily group windows into tabs, check out KDE Plasma, it can do this for you.

> A web app is an app after all, why shouldn't it benefit from what we have learn about efficiency when working with desktop apps?

If it truly is an "app", then it already does. If it does not (e.g. Amazon, Facebook, Google) then it's probably just a website, and having a whole separate window for that one site, offers little benefit. Though you could do this already in your browser - just pull some tabs into a new window! What's the big difference between that and WebCatalog re-implementing a tab interface?
