### ISSUE TITLE
Add backup/restore support

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#64]
> Hi Lam, do you think backup / restore apps via online Account, or iCloud / Dropbox / Google Drive is possible ? I just reinstalled the computer and reinstalling all the apps I created manually is a pain. best regards David Hoang

**Comment by MichaelTunnell** [comment]
I'd prefer the ability to just backup the apps locally rather than locked to any kind of online account. However, with Dropbox and stuff like that you could do both with a local backup.

I'd prefer an Import/Export tool. I don't need the sessions/logins to be saved because that could be a security issue but auto-importing all of the apps I want to use would be nice to have.
