### ISSUE TITLE
bug: Google Meet screen sharing is not working

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#649]
# Bug Report
**Current Behavior:**

<img width="1109" alt="Screen Shot 2020-04-06 at 11 47 10 PM" src="https://user-images.githubusercontent.com/1548835/78583418-03416680-7861-11ea-8ead-b4cf726e9eb6.png">

**Expected Behavior:**

**Steps to Reproduce:**

**Additional Context**

**Comment by coertel-ivadolabs** [comment]
Dito, on Catalina. No request for permission to access screen, either.

**Comment by quanglam2807** [comment]
I'm aware of the bug but a fix won't be available soon. Still, I'll try my best to get it fix ASAP.

**Comment by lovozeto** [comment]
Hey, do we have an update on this bug? Still happening :(

**Comment by quanglam2807** [comment]
The app does support screen sharing but somehow, it doesn’t work with Google Meet. 

Anyway, good news, Chrome-based Google Meet will be fixed in the update.

**Comment by coertel-ivadolabs** [comment]
With Chrome-based Meet, now on Big Sur, I get a slightly different error message saying "You must grant permission in order to screenshare".

I granted the screen-recording permission by manually adding the Google Meet app to the list in the Mac OS system preferences.

The error dialog keeps on popping up though. Also, I only get a Chrome-popup, no Mac OS system pop up.

Is there currently any way to use screen-sharing in Google Meet?

**Comment by boris-bc** [comment]
One year later...
Now it's not even possible to choose the engine, you need to use a different app. And BTW, it doesn't work there either.
