### ISSUE TITLE
feature: add Dark Reader integration

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#673]
# Feature Request
**Describe the Feature Request**

> I tried Franz a while ago, and recently discovered Ferdi: https://getferdi.com Now - that has one feature that I think your Apps would really, really make me happy to see... Dark Reader integration! Honestly, take a look at how Ferdi does it with the integrated preferences and I am sure you will see too.

https://github.com/darkreader/darkreader

**Describe Preferred Solution**

**Describe Alternatives**

**Additional Context**

**Comment by marcusquinn** [comment]
Keep up the great work! :)

**Comment by marcusquinn** [comment]
Tell you what, this would be so good for eye and sleep health, I'll purchase another 20 licences for my team if you can fast-track this one ;)

**Comment by quanglam2807** [comment]
Thanks a lot for the suggestion and encouragement ! It'll be available in the next update :)

**Comment by quanglam2807** [comment]
It's now available: https://github.com/atomery/webcatalog/releases/tag/v20.4.0. Please give a try! The only thing I don't like: sometimes, a web page would be loaded in white theme first before Dark Reader turns the page dark. It doesn't happen with Chrome + Dark Reader but I can't find a good solution to resolve it.

**Comment by marcusquinn** [comment]
Great stuff, it looks fantastic to my long-serving late-night eyes! 😎 

I'll DM you to figure out how to keep good to my promise on the licence purchases 😁 

So-far, so good. I don't think you can do anything about the FOUCs for sites that have render-blocking css but usually once the cache is warmed they are better. I only see them very occasionally anyway, so it's not a bother to me.

A couple of feedbacks...

1. Can you make the default values for Sepia +10% for each please? (to match the defaults the extension has on installation in other browsers). Personally, I also like Contrast +10% as well, it's a bit healthier to avoid squinting and you might also find a nicer default too.
2. Sometime the Brightness, Contrast, Sepia, Greyscale settings are all showing as 0/NaaN in settings when first enabled (I've only tested in updated Electro WebApps so far). Maybe a bug, maybe just because I updated the Apps and it's something that a restart might fix.
3. Can you add an "Extensions" section to the main WebCatalog for setting the default values to save re-doing on every new WebApp created?

This feature and your excellent work makes me very happy!

**Comment by marcusquinn** [comment]
Also, try comparing https://soundcloud.com with Electron & Dark Reader to Safari/Chrome etc.

It looks like it might be an issue with iFrames not having it?

Similar issue in the title area of Xero too. Strange eh!

**Comment by marcusquinn** [comment]
Also worth checking https://www.bbc.co.uk/news with the latest Electron version. I'm getting an unusual grey background even without Dark Reader running but could be related:

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/6428977/79403467-e571b100-7f86-11ea-9d47-7f402648cd9e.png">

**Comment by quanglam2807** [comment]
Thanks for reporting the previous bug! 

> Can you make the default values for Sepia +10% for each please? (to match the defaults the extension has on installation in other browsers). Personally, I also like Contrast +10% as well, it's a bit healthier to avoid squinting and you might also find a nicer default too.
About the default settings. I just tried Dark Reader on Chrome & Windows, they both use 0 as default value for Sepia. Do you mean something different?

**Comment by marcusquinn** [comment]
> Tell you what, this would be so good for eye and sleep health, I'll purchase another 20 licences for my team if you can fast-track this one ;)

20 Licences now purchased!

And I'll purchase another 20 when you add all the other recommend Apps, Tabs & Bookmark Bar ;)

Keep up the great work!
