### ISSUE TITLE
feature: Google Drive Doesn't Open "Native" files Internally 

### ISSUE THREAD

**Issue by jonsnelson** [webcatalog/webcatalog-legacy#800]
# Bug Report
**Current Behavior:**
Currently, Google Drive opens Google Docs and Google Sheets files in the browser- not within the app.  (Perhaps this intentional to facilitate printing?)

**Expected Behavior:**
These "native files" should ideally open _internally_ -in a pop up window- inside Google Drive.  

**Steps to Reproduce:**
Double left click on Google Docs or Google Sheets from within the app and they automatically open in the system browser.

**Additional Context**
*Google Drive in an electron wrapper doesn't seem to allow right click/context menu options, so I _don't think_ Open in New Window/Open in Browser is a solution. 
*Usually in an electron wrapper, these "native" Google files open in a pop up window, without a problem.

**Comment by quanglam2807** [comment]
Thanks for the feedback!

The default behavior of WebCatalog is that if the web app tries to open a link in new tab, WebCatalog will open it in the browser unless the link matches certain predefined rules.

I’ll make changes so that documents open in new window instead of in the browser. Optimally, I want it to open the document in the Google Docs app if available but let’s leave that for later. :)

**Comment by jonsnelson** [comment]
> Optimally, I want it to open the document in the Google Docs app if available but let’s leave that for later. :)

That indeed would be awesome- as a future possibility!
