### ISSUE TITLE
No Tool Bar 

### ISSUE THREAD

**Issue by sampler** [webcatalog/webcatalog-legacy#828]
Mac OS 10.14.6.   Google Chrome default

I chose built-in NY times app; however no tool bar appears.  If I go to preferences, I get the ordinary Chrome preferences pages with tool bar. I can of course add extensions, but without a tool bar they too are inivisble.

Not listing as a bug because I might be missing something basic.

**Comment by quanglam2807** [comment]
Thank you for asking. At the moment, if you use Google Chrome as browser engine, new app will be installed in special Chrome app mode which doesn't support toolbar. An option to install app in Chrome normal mode will be added in the next major update. 

Also, as this issue is a duplicate, let's move the discussion to #672.

**Comment by sampler** [comment]
Thanks. I look forward to the update.
