### ISSUE TITLE
bug: When using github app external links don't open in browser

### ISSUE THREAD

**Issue by Naatan** [webcatalog/webcatalog-legacy#849]
# Bug Report
**Specifications:**
- App Version: 8.14.1
- OS (macOS, Windows, Linux): macOS

**Description:**
When opening a link on github (in this case a circleci link on a failed integration) it opens it inside the app window, rather than in my default browser.

**Steps to Reproduce:**
Click a link on github that goes to an external site

**Comment by quanglam2807** [comment]
Thank you for reporting this. The link is not opened in browser because GitHub doesn't set the link to open in new tab. At the moment, WebCatalog detects external links and opens them in browser ONLY the link is opened with `target='_blank'`. I'm afraid forcing all external links, including links that normally are opened in the same browser tab, to open in new window/externally might break web apps. 

Anyway, I'll attempt to force this behavior in the next update. Hopefully, it won't break anything.

**Comment by quanglam2807** [comment]
Fixed with https://github.com/atomery/juli/pull/6
