### ISSUE TITLE
bug: Google Voice badge count is wrong when there's an error code

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#873]
> I created a Google Voice app and sometimes it shows a huge number (573!) of new calls on the Dock icon badge. If I Reload the Page, it clears for a moment, but then the number comes back. Kevin

**Comment by swrobel** [comment]
This happens when you have a specific message selected. It shows the phone number that the message is from in the <title> which causes WebCatalog to think it's a count that should be shown on the badge. 

No badge:
<img width="149" alt="Screen Shot 2021-01-08 at 11 25 27 AM" src="https://user-images.githubusercontent.com/157270/104055835-48097d80-51a4-11eb-9027-c4c5b473b168.png">

Message selected, badge shows:
<img width="127" alt="Screen Shot 2021-01-08 at 11 24 08 AM" src="https://user-images.githubusercontent.com/157270/104055850-4fc92200-51a4-11eb-80c4-d665a6b0e5df.png">
<img width="59" alt="Screen Shot 2021-01-08 at 11 25 41 AM" src="https://user-images.githubusercontent.com/157270/104055859-53f53f80-51a4-11eb-8663-827f0026a344.png">

**Comment by quanglam2807** [comment]
Thank you for reporting, Stephan. 

Currently, the app just looks for the number in the brackets. Regex rule:`/(?<=[([{])(\d*?)(?=[}\])])/`. I'm still not sure what would be the best way to handle this edge case.
