### ISSUE TITLE
bug: getaddrinfo ENOTFOUND github.com

### ISSUE THREAD

**Issue by kurstah** [webcatalog/webcatalog-legacy#890]
![image](https://user-images.githubusercontent.com/67028979/84835295-ac4ad100-b009-11ea-9804-36565bb15ba7.png)

**Comment by SchwiftyGamer** [comment]
I fixed this by going to Preferences -> Advanced -> Preferred Browser Engine -> Change to Chrome.

This fixed it for me and will now install. Hope this works for you.

**Comment by quanglam2807** [comment]
Thank you for helping, @SchwiftyGamer. I'm glad that you managed to find a workaround for this problem. But actually, Chrome engine doesn't offer as many features as Electron. 

The bug occurs because WebCatalog fails to download this file: https://github.com/atomery/webcatalog/releases.atom because of DNS problem. @Kurstah  @SchwiftyGamer Would you mind trying to access the link to see if you're able to?

**Comment by SchwiftyGamer** [comment]
Still not working using the Electron engine, getting the same error.

**Comment by quanglam2807** [comment]
The bug is now fixed in v22.2.1. I hope it works well for everyone.
