### ISSUE TITLE
Chrome overrides taskbar icon with the page icon upon load

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#9]
High-res icon is displayed in launcher. However, Chrome will override Taskbar icon with the page icon upon load. This lowers your Taskbar icon resolution.

**Comment by michaldybczak** [comment]
From what I noticed, this only happens if you pin it to the taskbar. So basically, after pinning it changes the icon and becomes simply another Chrome/Chromium launcher, not a specific to the chosen app/site. So to keep it using one must always open the main app and open the apps from the installed list. This is far from ideal (multiple steps must be taken to launch an app) and it gives me low res icon but since webapps support was broken on Chrome/Chromium, this is the only way so far.
