### ISSUE TITLE
bug: the app takes massive resources in all instances

### ISSUE THREAD

**Issue by quanglam2807** [webcatalog/webcatalog-legacy#905]
> WebCatalog takes massive resources in all instances. What do you need from my side in order to find out whats wrong? Steven

If anyone's facing this problem, please let me know.

**Comment by zyexal** [comment]
It's mainly about CPU.

It looks like the problem is somehow related to the rendering. When I minimise the apps CPU load drops to a minimum. I also could see, that `cinnamon --replace` takes at least ~40% CPU instead of ~4% when any instance is not minimized. Multiple instances potentiate the problem.
The WebCatalog processes with high loads have the following parameters:
`--type=gpu-process` and
`--type=render --node-integration --no-sandbox`

Chrome is knowingly taking some resources, but a way less than WebCatalog in my case. I've permanently 10-50 Tabs open without issues. A single WebCatalog app causes already high loads.

**Comment by quanglam2807** [comment]
Thank you for information, @zyexal. It really helps to clarify the issue.

I just updated the app to Electron 8.4.0 which fixed a 100% CPU bug on macOS. I'm not sure if it's related to this issue but please give it a try and let me know if it resolves this problem.

**Comment by zyexal** [comment]
Unfortunately, I see the following message for all Apps and the App can not get minified anymore (pops up ride away again):
![image](https://user-images.githubusercontent.com/439526/87675000-1d031b80-c777-11ea-9176-a03d6ed02e98.png)

If the App is not set to be fullscreen it works also not so well, but without massive resource usage!

**Comment by zyexal** [comment]
Additionally, I am not allowed to switch workspaces anymore. The Apps forcing focus on themself. Have to wait for the fix. 

**Rollback to previews version appreciated!**

**Comment by quanglam2807** [comment]
> Additionally, I am not allowed to switch workspaces anymore. The Apps forcing focus on themself. Have to wait for the fix.
> 
> **Rollback to previews version appreciated!**

Can you share more details? I'll fix it quickly.

**Comment by zyexal** [comment]
I'm using two workspaces on my linux machine (cinnamon desktop). When I open any of the WebCatalog apps at desktop one and try to switch to desktop two the screen blinks short and switches back to desktop one. Additionally, the App is in the focus all the time and minimizing impossible.
Not sure how to describe better

**Comment by zyexal** [comment]
Close, please. Perfect work!

**Comment by zyexal** [comment]
I was commenting, that the resources are fine after the latest update, but I was wrong (sry).

**Comment by quanglam2807** [comment]
@zyexal :( I think we would have to wait for Chromium/Electron to get better with resource management. For now, I would suggest you to utilize the "Hibernation" option to freeze unused workspaces.

**Comment by palsch** [comment]
Hello @quanglam2807 , I have the same issue with hight CPU load on Ubuntu. Did you tried the 9.1.2 electron version already?

**Comment by quanglam2807** [comment]
Thanks for the suggestion, @palsch. I haven't tried 9.1.2 as the app is still using Electron 8.x. Normally, I skip odd versions of Electron to avoid dealing bugs happening after every Electron upgrade. So hopefully, when Electron 10.x is released, this issue will be resolved. 

Also, I'm not sure if this issue affects all platforms or only Linux. Personally, for me, on Mac, the app doesn't have this issue.

**Comment by marcusquinn** [comment]
Must say, I did notice CPU usage in Activity Monitor (Mac) seemed to jump to much higher averages compared to before. I think it was around the time of an Electron version update too but difficult to say.

I used to leave all Apps open and they'd float around 1% but I'm noticing them float around 10% CPU now so tending to quit and reopen a lot instead.

**Comment by palsch** [comment]
On my Ubuntu I am using Microsoft OneNote with WebCatalog. 
At Idle mode it uses 8% from my CPU (Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz).
If I open the OneNote with Chrome, it uses only 1% in Idle mode.
So each app, that is opened with WebCatalog uses around 8% CPU, if you have too much opened Apps, you will get 100% usage only in idle mode.

**Comment by palsch** [comment]
Hi @quanglam2807,
currently I tried following electron based OneNote application ([p3x-OneNote](https://github.com/patrikx3/onenote)), and the CPU usage is comparable to them from Chrome (see screenshots I did below). So it looks like, it is not an issue of the electron, or maybe the issue was fixed with the latest electron version that is used by this application (9.1.2).

WebCatalog OneNote (Electron):
![image](https://user-images.githubusercontent.com/1561681/89707686-d1582200-d970-11ea-9d83-4b360b5fa43b.png)

p3x OneNote (Electron):
![image](https://user-images.githubusercontent.com/1561681/89707696-e339c500-d970-11ea-877a-86857e6a68e0.png)

As @zyexal already said, it looks like WebCatalog App have high CPU usage and it increases the CPU usage of the display server (xorg) and KDE Plasma Desktop (kwin_x11).

**Comment by quanglam2807** [comment]
Thank you for all the details, everyone!

I discovered that the loading animation was kept running behind the web view and used quite a lot of CPU so I've removed it. Please give it a try and see if it fixes the problem. If this remains unfixed, I'll try to upgrade the app to Electron 9 early.

**Comment by palsch** [comment]
Hi @quanglam2807 , 
I tested it currently with and without fix, and it looks like you found the solution. **Now it works as desired.** Thank you!
Could you make a new WebCatalog release, so we can use it in production.
Best regards
Paul

**Comment by quanglam2807** [comment]
@palsch Thank you for testing! It sounds great. For production, you can use the current version of WebCatalog to update the generated apps to the latest version. WebCatalog's updates and generates apps' updates are independent from each other. 

I'll leave this thread open for now (until we're all sure the problem is fixed).

**Comment by zyexal** [comment]
Hi @quanglam2807,

I'm happy to confirm:
_Google Chat, Google Calendar, Trello, Discord:_ 
![image](https://user-images.githubusercontent.com/439526/89878294-a1538d80-dbc1-11ea-999c-21ab445009a7.png)

My system is relaxed again :+1: 

Thanks a lot!
Steven

**Comment by quanglam2807** [comment]
@zyexal Thank you so much for testing! I didn't expect such a small change could fix this issue. I'll close this issue for now. If the bug somehow occurs again, please let me know.

**Comment by marcusquinn** [comment]
All good for may, maybe even a little faster.

**Comment by edmundlaugasson** [comment]
I have to admit, that even now with version 27.4.0 and using 6 Google Drive apps in multisite app will overwhelm the 8-core CPU computer....
