### ISSUE TITLE
bug: Figma not working

### ISSUE THREAD

**Issue by hacknug** [webcatalog/webcatalog-legacy#994]
figma support is broken as of version v10.0.0-alpha.2

**Comment by quanglam2807** [comment]
Thank you for reporting, @hacknug. This bug is caused by Electron 10: https://github.com/electron/electron/issues/25127 and currently only affects pre-release channel. We'll have to wait for Electron team to response.

I'm sorry that it's not possible downgrade an app from pre-release version to stable version, you'd probably have to leave pre-release channel and reinstall Figma.

**Comment by hacknug** [comment]
@quanglam2807 latest beta introduced a regression for Figma (v10.0.0-alpha.13)

**Comment by quanglam2807** [comment]
The workaround fix causes affects security and brings some bugs so I've reverted it: https://github.com/atomery/juli/pull/116

I'm sorry but we'll have to wait for Electron to be fixed: https://github.com/electron/electron/issues/25127

**Comment by hacknug** [comment]
No problem. Thanks for the heads up!

**Comment by quanglam2807** [comment]
I've downgraded to electron@9. I can no longer wait to release v10 to everyone.
